---

- name: Include os-specific vars
  include: 'vars.yml'

- name: Include distribution installation
  include: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- name: make motd
  template: src=motd.j2 dest=/etc/motd owner=root group={{ motd_group }} mode={{ motd_mode }}